name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Run Coverage (optional)
        run: NODE_ENV=test npm run coverage

      - name: Upload coverage report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/ 

      - name: Security Check (npm audit)
        run: npm audit --audit-level=moderate # level anpassbar

  docker_build_and_push:
    needs: build_and_test
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${{ github.sha }}

  security_scan:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Application with Docker Compose
        run: docker compose up -d
        env:
          NODE_ENV: development

      - name: Pull OWASP ZAP Docker Image
        run: docker pull zaproxy/zap2docker-stable

      - name: Run OWASP ZAP Security Scan
        run: |
          docker run --network="host" zaproxy/zap2docker-stable zap-baseline.py \
          -t http://localhost:3000 \
          -r zap_report.html

      - name: Upload OWASP ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap_report.html

      - name: Stop Application
        run: docker-compose down
