name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Run Coverage (optional)
        run: NODE_ENV=test npm run coverage

      - name: Upload Coverage Report (optional)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install

      - name: Security Check (npm audit)
        run: npm audit --audit-level=moderate

  docker_build_and_push:
    needs:
      - lint
      - test
      - audit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${{ github.sha }}

  deploy_and_scan:
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && success()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Container Locally
        run: |
          docker run -d --name ci-cd-demo -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo:${{ github.sha }}
          # Warte, bis die Anwendung vollständig gestartet ist
          sleep 20

      - name: Wait for Application to be Accessible
        run: |
          echo "Waiting for the application to be accessible on localhost..."
          until curl --silent --fail "http://localhost:3000"; do
            echo "Waiting for the server to be ready..."
            sleep 5
          done
          echo "Application is accessible."

      - name: Install OWASP ZAP
        run: |
          sudo apt update
          sudo apt install -y snapd
          sudo snap install zaproxy --classic

      - name: Run OWASP ZAP Security Scan
        run: |
          zaproxy -cmd -quickurl http://localhost:3000 -quickout /tmp/zap-report.html

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-scan-report
          path: /tmp/zap-report.html

      - name: Stop and Remove Container
        run: |
          docker stop ci-cd-demo
          docker rm ci-cd-demo
